console.log("Problem 2");
console.log("Each new term in the Fibonacci sequence is generated by \
adding the previous two terms. By starting with 1 and 2, the first 10 \
terms will be:");
console.log("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
console.log("By considering the terms in the Fibonacci sequence whose \
values do not exceed four million, find the sum of the even-valued terms");

var sum = 0; // Initial values {1, 2} given. 2 is even and initialised in sum.
var a = 1;
var b = 2;
var fib = 0;

while(a <= 4000000) {
    if(a % 2 === 0) {
        sum += a;
    }
    fib = a + b;
    a = b;
    b = fib;
}

console.log("sum = " + sum);